/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SnorkelingRouteImport } from './routes/snorkeling'
import { Route as OralHistoryRouteImport } from './routes/oral-history'
import { Route as MapRouteImport } from './routes/map'
import { Route as FloraFaunaRouteImport } from './routes/flora-fauna'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FieldNotesGeologyRouteImport } from './routes/field-notes.geology'
import { Route as FieldNotesBiogeochemistryRouteImport } from './routes/field-notes.biogeochemistry'
import { Route as FieldNotesAnthropologyRouteImport } from './routes/field-notes.anthropology'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SnorkelingRoute = SnorkelingRouteImport.update({
  id: '/snorkeling',
  path: '/snorkeling',
  getParentRoute: () => rootRouteImport,
} as any)
const OralHistoryRoute = OralHistoryRouteImport.update({
  id: '/oral-history',
  path: '/oral-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FloraFaunaRoute = FloraFaunaRouteImport.update({
  id: '/flora-fauna',
  path: '/flora-fauna',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesGeologyRoute = FieldNotesGeologyRouteImport.update({
  id: '/geology',
  path: '/geology',
  getParentRoute: () => FieldNotesRoute,
} as any)
const FieldNotesBiogeochemistryRoute =
  FieldNotesBiogeochemistryRouteImport.update({
    id: '/biogeochemistry',
    path: '/biogeochemistry',
    getParentRoute: () => FieldNotesRoute,
  } as any)
const FieldNotesAnthropologyRoute = FieldNotesAnthropologyRouteImport.update({
  id: '/anthropology',
  path: '/anthropology',
  getParentRoute: () => FieldNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRouteWithChildren
  '/flora-fauna': typeof FloraFaunaRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
  '/field-notes/anthropology': typeof FieldNotesAnthropologyRoute
  '/field-notes/biogeochemistry': typeof FieldNotesBiogeochemistryRoute
  '/field-notes/geology': typeof FieldNotesGeologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRouteWithChildren
  '/flora-fauna': typeof FloraFaunaRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
  '/field-notes/anthropology': typeof FieldNotesAnthropologyRoute
  '/field-notes/biogeochemistry': typeof FieldNotesBiogeochemistryRoute
  '/field-notes/geology': typeof FieldNotesGeologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRouteWithChildren
  '/flora-fauna': typeof FloraFaunaRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
  '/field-notes/anthropology': typeof FieldNotesAnthropologyRoute
  '/field-notes/biogeochemistry': typeof FieldNotesBiogeochemistryRoute
  '/field-notes/geology': typeof FieldNotesGeologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/flora-fauna'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
    | '/field-notes/anthropology'
    | '/field-notes/biogeochemistry'
    | '/field-notes/geology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/flora-fauna'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
    | '/field-notes/anthropology'
    | '/field-notes/biogeochemistry'
    | '/field-notes/geology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/flora-fauna'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
    | '/field-notes/anthropology'
    | '/field-notes/biogeochemistry'
    | '/field-notes/geology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConditionsRoute: typeof ConditionsRoute
  ConservationRoute: typeof ConservationRoute
  FieldNotesRoute: typeof FieldNotesRouteWithChildren
  FloraFaunaRoute: typeof FloraFaunaRoute
  MapRoute: typeof MapRoute
  OralHistoryRoute: typeof OralHistoryRoute
  SnorkelingRoute: typeof SnorkelingRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snorkeling': {
      id: '/snorkeling'
      path: '/snorkeling'
      fullPath: '/snorkeling'
      preLoaderRoute: typeof SnorkelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-history': {
      id: '/oral-history'
      path: '/oral-history'
      fullPath: '/oral-history'
      preLoaderRoute: typeof OralHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flora-fauna': {
      id: '/flora-fauna'
      path: '/flora-fauna'
      fullPath: '/flora-fauna'
      preLoaderRoute: typeof FloraFaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes/geology': {
      id: '/field-notes/geology'
      path: '/geology'
      fullPath: '/field-notes/geology'
      preLoaderRoute: typeof FieldNotesGeologyRouteImport
      parentRoute: typeof FieldNotesRoute
    }
    '/field-notes/biogeochemistry': {
      id: '/field-notes/biogeochemistry'
      path: '/biogeochemistry'
      fullPath: '/field-notes/biogeochemistry'
      preLoaderRoute: typeof FieldNotesBiogeochemistryRouteImport
      parentRoute: typeof FieldNotesRoute
    }
    '/field-notes/anthropology': {
      id: '/field-notes/anthropology'
      path: '/anthropology'
      fullPath: '/field-notes/anthropology'
      preLoaderRoute: typeof FieldNotesAnthropologyRouteImport
      parentRoute: typeof FieldNotesRoute
    }
  }
}

interface FieldNotesRouteChildren {
  FieldNotesAnthropologyRoute: typeof FieldNotesAnthropologyRoute
  FieldNotesBiogeochemistryRoute: typeof FieldNotesBiogeochemistryRoute
  FieldNotesGeologyRoute: typeof FieldNotesGeologyRoute
}

const FieldNotesRouteChildren: FieldNotesRouteChildren = {
  FieldNotesAnthropologyRoute: FieldNotesAnthropologyRoute,
  FieldNotesBiogeochemistryRoute: FieldNotesBiogeochemistryRoute,
  FieldNotesGeologyRoute: FieldNotesGeologyRoute,
}

const FieldNotesRouteWithChildren = FieldNotesRoute._addFileChildren(
  FieldNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConditionsRoute: ConditionsRoute,
  ConservationRoute: ConservationRoute,
  FieldNotesRoute: FieldNotesRouteWithChildren,
  FloraFaunaRoute: FloraFaunaRoute,
  MapRoute: MapRoute,
  OralHistoryRoute: OralHistoryRoute,
  SnorkelingRoute: SnorkelingRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
